# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sendgrid}
  s.version = "0.1.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephen Blankenship"]
  s.date = %q{2011-03-16}
  s.description = %q{This gem allows simple integration between ActionMailer and SendGrid. 
                         SendGrid is an email deliverability API that is affordable and has lots of bells and whistles.}
  s.email = %q{stephenrb@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/sendgrid.rb",
    "lib/sendgrid/wrappers.rb",
    "test/sendgrid_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/stephenb/sendgrid}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{A gem that allows simple integration of ActionMailer with SendGrid (http://sendgrid.com)}
  s.test_files = [
    "test/sendgrid_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

